steps:
  - label: Build and Create Release
    command: bash ./.scripts/build.sh $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BUILD_NUMBER
    plugins:
      docker#v1.1.1:
        image: "microsoft/aspnetcore-build"
        workdir: /app
        environment:
          - OctopusApiKey=$OctopusApiKey
    retry:
      manual:
        permit_on_passed: true