steps:
  - label: Build and Create Release
    command: bash ./.scripts/build.sh $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BUILD_NUMBER
    agents:
      os: "ubuntu-docker"
    retry:
      manual:
        permit_on_passed: true

  - wait

  - label: Package and Publish
    command: test.cmd
    agents:
      os: "windows"
    retry:
      manual:
        permit_on_passed: true
        
  # - label: Package and Publish
  #   command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/package.ps1 -VersionNumber $env:BUILDKITE_BUILD_NUMBER -Id $env:BUILDKITE_PIPELINE_SLUG -OctopusApiKey $env:OctopusApiKey"
  #   agents:
  #     os: "windows"
  #   retry:
  #     manual:
  #       permit_on_passed: true

  # - wait

  # - label: Deploy to Sandbox
  #   command: ./.scripts/deploy.ps1 -VersionNumber $BUILDKITE_BUILD_NUMBER -Id $BUILDKITE_PIPELINE_SLUG -OctopusApiKey $OctopusApiKey -Environment sandbox
  #   agents:
  #     os: "windows"
  #   retry:
  #     manual:
  #       permit_on_passed: true

  # - wait 

  # - label: Deploy to Non-Prod
  #   command: ./.scripts/deploy.ps1 -VersionNumber $BUILDKITE_BUILD_NUMBER -Id $BUILDKITE_PIPELINE_SLUG -OctopusApiKey $OctopusApiKey -Environment nonprod
  #   agents:
  #     os: "windows"
  #   retry:
  #     manual:
  #       permit_on_passed: true