steps:
  - command: bash ./.buildkite/build.sh $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BUILD_NUMBER
    plugins:
      docker#v1.1.1:
        image: "node:8"
        workdir: /app
    retry:
      manual:
        permit_on_passed: true
