steps:
  - label: Build and Create Release
    command: bash ./.scripts/build.sh $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BUILD_NUMBER
    agents:
      os: "ubuntu-docker"
    retry:
      manual:
        permit_on_passed: true

  - wait
        
  - label: Package and Publish
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/package.ps1"
    agents:
      os: "windows"

    retry:
      manual:
        permit_on_passed: true

  - wait

  - label: Deploy to Sandbox - Asia Pacific (Sydney)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "Asia Pacific (Sydney)"
      Environment: "sandbox"
    retry:
      manual:
        permit_on_passed: true

  # - wait 

  # - label: Deploy to Non-Prod
  #   command: ./.scripts/deploy.ps1 -VersionNumber $BUILDKITE_BUILD_NUMBER -Id $BUILDKITE_PIPELINE_SLUG -OctopusApiKey $OctopusApiKey -Environment nonprod
  #   agents:
  #     os: "windows"
  #   retry:
  #     manual:
  #       permit_on_passed: true