steps:
  - label: Build and Create Release
    command: bash ./.scripts/build.sh $BUILDKITE_PIPELINE_SLUG $BUILDKITE_BUILD_NUMBER
    agents:
      os: "ubuntu-docker"
    retry:
      manual:
        permit_on_passed: true

  - wait
        
  - label: Package and Publish
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/package.ps1"
    agents:
      os: "windows"
    retry:
      manual:
        permit_on_passed: true

  - wait

  - label: Deploy to Sandbox - Asia Pacific (Sydney)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "Asia Pacific (Sydney)"
      Environment: "sandbox"
    retry:
      manual:
        permit_on_passed: true

  - label: Deploy to Sandbox - EU (Ireland)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "EU (Ireland)"
      Environment: "sandbox"
    retry:
      manual:
        permit_on_passed: true

  - label: Deploy to Sandbox - US East (N. Virginia)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "US East (N. Virginia)"
      Environment: "sandbox"
    retry:
      manual:
        permit_on_passed: true

  - wait 

  - label: Deploy to Non-Prod - Asia Pacific (Sydney)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "Asia Pacific (Sydney)"
      Environment: "nonprod"
    retry:
      manual:
        permit_on_passed: true

  - label: Deploy to Non-Prod - EU (Ireland)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "EU (Ireland)"
      Environment: "nonprod"
    retry:
      manual:
        permit_on_passed: true

  - label: Deploy to Non-Prod - US East (N. Virginia)
    command: powershell.exe -ExecutionPolicy Bypass -Command "./.scripts/deploy.ps1"
    agents:
      os: "windows"
    env:
      Tenant: "US East (N. Virginia)"
      Environment: "nonprod"
    retry:
      manual:
        permit_on_passed: true