AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:
    Environment: 
        Type: String
        Default: missingEnvironmentValue
        Description: Environment / Account Type

Resources:
    OctopusBucket:
        Type: "AWS::S3::Bucket"
        Properties: 
          BucketName: !Sub 'jaimen-hello-build-kite-new-${AWS::Region}-${Environment}'